fix compile error C2664 caused by std::make_pair<> in VS2012
git-svn-id: svn+ssh://svn.pointclouds.org/pcl/trunk@8101 a9d63959-f2ad-4865-b262-bf0e56cfafb6